trigger:
- master

pool:
  vmImage: windows-latest
  
variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:
- stage: build
  jobs:
  - job: TerraformSetup 
    displayName: 'Create Ressources with Terraform'
    steps:
    - script: ls
      displayName: 'first'

    - task: Terraform@2
      inputs:
        TemplatePath: 'main.tf'
        Arguments: 'init'
        PlanPath: 'main.tfplan'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'sp-terraform-Schulung'
        ManageState: true
        SpecifyStorageAccount: true
        StorageAccountResourceGroup: 'rg-aschmidt-cloudwalker'
        StorageAccountRM: 'stacloudwalkerterraform'
        StorageContainerName: 'c-cloudwalker-terraform'

