# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest
  
variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:
- stage: build
  jobs:
  - job: TerraformSetup 
    displayName: 'Create Ressources with Terraform'
    steps:
    - script: ls
      displayName: 'first'
    - task: Terraform@2
      displayName: 'Terraform init'
      inputs:
        TemplatePath: '~/main.tf'
        Arguments: 'init -update'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'sp-terraform-Schulung'
        ManageState: true
        SpecifyStorageAccount: true
        StorageAccountResourceGroup: 'rg-aschmidt-cloudwalker'
        StorageAccountRM: 'stacloudwalkerterraform'
        StorageContainerName: 'c-cloudwalker-terraform'
    - task: Terraform@2
      displayName: 'Terraform plan'
      inputs:
        TemplatePath: 'main.tf'
        Arguments: 'plan -out main.tfplan'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'sp-terraform-Schulung'
        ManageState: true
        SpecifyStorageAccount: true
        StorageAccountResourceGroup: 'rg-aschmidt-cloudwalker'
        StorageAccountRM: 'stacloudwalkerterraform'
        StorageContainerName: 'c-cloudwalker-terraform'
    - task: Terraform@2
      displayName: 'terraform apply'
      inputs:
        TemplatePath: 'main.tf'
        Arguments: 'apply'
        PlanPath: 'main.tfplan'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'sp-terraform-Schulung'
        ManageState: true
        SpecifyStorageAccount: true
        StorageAccountResourceGroup: 'rg-aschmidt-cloudwalker'
        StorageAccountRM: 'stacloudwalkerterraform'
        StorageContainerName: 'c-cloudwalker-terraform'

