trigger:
- master

pool:
  vmImage: windows-latest
  
variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:
- stage: build
  jobs:
  - job: TerraformSetup 
    displayName: 'Create Ressources with Terraform'
    steps:
    - script: ls
      displayName: 'first'
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init
        terraform plan -out=terraform.tfplan
      displayName: 'Terraform Plan'
