trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:
- stage: tfdestroy
  jobs:
  - job: destroy
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-upgrade'
        backendServiceArm: 'sp-terraform-Schulung'
        backendAzureRmResourceGroupName: 'rg-aschmidt-cloudwalker'
        backendAzureRmStorageAccountName: 'stacloudwalkerterraform'
        backendAzureRmContainerName: 'c-cloudwalker-terraform'
        backendAzureRmKey: 'prod.terraform.tfstate'
    - task: TerraformTaskV4@4
      displayName: 'terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: -destroy -out main.destroy.tfplan -lock=false
        environmentServiceNameAzureRM: 'sp-terraform-Schulung'
    - task: TerraformTaskV4@4
      displayName: 'terraform apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-lock=false main.destroy.tfplan'
        environmentServiceNameAzureRM: 'sp-terraform-Schulung'